#!/usr/bin/env bash
set -euo pipefail

# 0. if we're on Windows, prepare MSVC first -------------------------------
if [[ "$OS" == "Windows_NT" ]]; then
  # Find the newest VS / Build‑Tools install via vswhere (ships with VS ≥2017)
  VSWHERE="/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
  if [[ -x "$VSWHERE" ]]; then
    VSROOT=$("$VSWHERE" -latest \
                      -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
                      -property installationPath | tr -d '\r')
    VSDEV="$VSROOT/Common7/Tools/VsDevCmd.bat"
  else
    # fallback – hard‑code BuildTools 2022
    VSDEV="/c/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/Tools/VsDevCmd.bat"
  fi

  # Convert to a proper Windows path for cmd.exe
  VSDEV_WIN=$(cygpath -w "$VSDEV")

  echo "→ Bootstrapping MSVC via: $VSDEV_WIN"

  set +H   # disable Bash history expansion once, affects the whole script

  PARSERS="lua vimdoc cpp python typescript tsx javascript json"


# write the temporary .bat -----------------------------------------------
TMPBAT="$(mktemp --suffix=.bat)"          # e.g. /tmp/tmp.XYZ123.bat
TMPBAT_WIN=$(cygpath -w "$TMPBAT")        # C:\Users\...\AppData\Local\Temp\tmp.XYZ123.bat

cat >"$TMPBAT" <<EOF
@echo off
rem  generated by nvim-config bootstrap
call "${VSDEV_WIN}" -arch=x64 -host_arch=x64
nvim --headless ^
  -c "Lazy! sync" ^
  -c "TSUpdateSync lua vimdoc cpp python typescript tsx javascript json" ^
  -c "qa"
EOF

echo "→ Bootstrapping via $TMPBAT_WIN"

# run the batch file *itself*, not a %VAR%
cmd.exe /C "\"$TMPBAT_WIN\""

 rm -f "$TMPBAT"                           # tidy up
exit $?
fi

# 1. Check prerequisites ---------------------------------------------------
if ! command -v nvim >/dev/null 2>&1; then
  echo "Neovim ≥0.9 is required — install it first." >&2
  exit 1
fi
if ! command -v git >/dev/null 2>&1; then
  echo "Git is required." >&2
  exit 1
fi

# 2. Ask Neovim for its own stdpaths ---------------------------------------
CONFIG_DIR=$(nvim -u NONE --headless -c 'lua print(vim.fn.stdpath("config"))' +qa 2>&1)
DATA_DIR=$(nvim  -u NONE --headless -c 'lua print(vim.fn.stdpath("data"))'   +qa 2>&1)
LAZY_PATH="$DATA_DIR/lazy/lazy.nvim"

echo "CONFIG_DIR: $CONFIG_DIR"
echo "DATA_DIR: $DATA_DIR"

# 3. Get your personal config ---------------------------------------------
if [ -d "$CONFIG_DIR/.git" ]; then
  git -C "$CONFIG_DIR" pull --ff-only
else
  git clone https://github.com/arturo-mayorga/nvim-config "$CONFIG_DIR"
fi

# 4. Bootstrap lazy.nvim ---------------------------------------------------
if [ ! -d "$LAZY_PATH" ]; then
  git clone --filter=blob:none https://github.com/folke/lazy.nvim "$LAZY_PATH"
fi

# 5. Install/upgrade plugins ----------------------------------------------
nvim --headless "+Lazy! sync | TSUpdateSync lua vimdoc cpp python typescript tsx javascript json" +qa

echo "✓ Neovim ready to go!"
